package com.limehee.jsonrpc.core;

import java.util.List;
import java.util.Optional;

/**
 * Immutable dispatcher result wrapper for single and batch requests.
 */
public final class JsonRpcDispatchResult {

    private final boolean batch;
    private final List<JsonRpcResponse> responses;

    /**
     * Creates a dispatcher result with immutable response storage.
     *
     * @param batch whether the source payload was processed as a batch request
     * @param responses response entries generated by dispatching
     */
    private JsonRpcDispatchResult(boolean batch, List<JsonRpcResponse> responses) {
        this.batch = batch;
        this.responses = List.copyOf(responses);
    }

    /**
     * Creates a non-batch result from an optional single response.
     *
     * @param response optional single response
     * @return dispatch result
     */
    public static JsonRpcDispatchResult single(Optional<JsonRpcResponse> response) {
        return new JsonRpcDispatchResult(false, response.stream().toList());
    }

    /**
     * Creates a non-batch result containing one response.
     *
     * @param response single response
     * @return dispatch result
     */
    public static JsonRpcDispatchResult single(JsonRpcResponse response) {
        return new JsonRpcDispatchResult(false, List.of(response));
    }

    /**
     * Creates a batch result.
     *
     * @param responses responses produced from batch processing
     * @return dispatch result
     */
    public static JsonRpcDispatchResult batch(List<JsonRpcResponse> responses) {
        return new JsonRpcDispatchResult(true, responses);
    }

    /**
     * Indicates whether the original payload was a batch request.
     *
     * @return {@code true} for batch payloads
     */
    public boolean isBatch() {
        return batch;
    }

    /**
     * Indicates whether there is at least one response to return.
     *
     * @return {@code true} when response list is non-empty
     */
    public boolean hasResponse() {
        return !responses.isEmpty();
    }

    /**
     * Returns all responses.
     *
     * @return immutable response list
     */
    public List<JsonRpcResponse> responses() {
        return responses;
    }

    /**
     * Returns the single response when this result is non-batch and non-empty.
     *
     * @return optional single response
     */
    public Optional<JsonRpcResponse> singleResponse() {
        if (batch || responses.isEmpty()) {
            return Optional.empty();
        }
        return Optional.of(responses.get(0));
    }
}
