name: Bug report
description: Report a reproducible bug
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please include enough detail to reproduce it.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is wrong?
      placeholder: Briefly describe the bug.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Library version
      description: Which version are you using?
      placeholder: e.g. 0.1.0-SNAPSHOT
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Runtime details
      placeholder: |
        - Java:
        - Spring Boot:
        - OS:
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or stack traces
      render: shell
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Include request/response payloads if relevant.
