package com.limehee.jsonrpc.spring.webmvc;

import com.limehee.jsonrpc.core.JsonRpcResponse;
import java.util.List;
import org.springframework.http.HttpStatus;

/**
 * Resolves HTTP status codes for JSON-RPC responses generated by the WebMVC transport layer.
 * <p>
 * JSON-RPC 2.0 itself is transport-agnostic and does not mandate specific HTTP status values. Implementations can
 * therefore customize status selection while keeping the JSON-RPC payload compliant with the specification.
 * </p>
 */
public interface JsonRpcHttpStatusStrategy {

    /**
     * Resolves the HTTP status for a single JSON-RPC response object.
     *
     * @param response single JSON-RPC response payload that will be serialized to the HTTP body
     * @return HTTP status to use for the transport response
     */
    HttpStatus statusForSingle(JsonRpcResponse response);

    /**
     * Resolves the HTTP status for a batch JSON-RPC response payload.
     *
     * @param responses JSON-RPC response objects generated for a batch request
     * @return HTTP status to use for the batch transport response
     */
    HttpStatus statusForBatch(List<JsonRpcResponse> responses);

    /**
     * Resolves the HTTP status when the request produced no JSON-RPC response payload (for example, notification-only
     * requests).
     *
     * @return HTTP status for notification-only outcomes
     */
    HttpStatus statusForNotificationOnly();

    /**
     * Resolves the HTTP status used when the request body cannot be parsed as valid JSON.
     *
     * @return HTTP status for parse errors
     */
    HttpStatus statusForParseError();

    /**
     * Resolves the HTTP status used when the request body size exceeds the configured limit.
     *
     * @return HTTP status for oversized request payloads
     */
    HttpStatus statusForRequestTooLarge();
}
